import type { MedicalDevice, ScanResult } from '../models/device.model';

export const SEED_DEVICES: MedicalDevice[] = [
  {
    id: 'dev-pm-001',
    name: 'Bedside Monitor A3',
    type: 'patient_monitor',
    manufacturer: 'MediCore',
    model: 'VitaLink Pro 450',
    serialNumber: 'MC-VL-88421',
    status: 'online',
    ward: 'ICU',
    bed: 'ICU-04',
    firmware: '3.2.1',
    lastSeen: Date.now(),
    connectedAt: Date.now() - 1000 * 60 * 48,
    metrics: { heartRate: 78, spo2: 98, systolic: 122, diastolic: 78, respiratoryRate: 16, temperature: 36.7, battery: 92 },
    alerts: [],
  },
  {
    id: 'dev-ip-002',
    name: 'Infusion Pump B2',
    type: 'infusion_pump',
    manufacturer: 'FlowMed',
    model: 'InfuSmart X9',
    serialNumber: 'FM-IS-22019',
    status: 'online',
    ward: 'Ward 3',
    bed: 'W3-12',
    firmware: '2.8.0',
    lastSeen: Date.now(),
    connectedAt: Date.now() - 1000 * 60 * 120,
    metrics: { infusionRate: 42, battery: 68 },
    alerts: [
      {
        id: 'al-1',
        severity: 'warning',
        message: 'Infusion bag volume below 15%',
        timestamp: Date.now() - 1000 * 60 * 8,
        acknowledged: false,
      },
    ],
  },
  {
    id: 'dev-vt-003',
    name: 'Ventilator C1',
    type: 'ventilator',
    manufacturer: 'AeroLife',
    model: 'RespiraMax 7',
    serialNumber: 'AL-RM-11004',
    status: 'online',
    ward: 'ICU',
    bed: 'ICU-01',
    firmware: '4.1.3',
    lastSeen: Date.now(),
    connectedAt: Date.now() - 1000 * 60 * 360,
    metrics: { respiratoryRate: 14, tidalVolume: 480, spo2: 96, battery: 100 },
    alerts: [],
  },
  {
    id: 'dev-ecg-004',
    name: 'ECG Station D4',
    type: 'ecg',
    manufacturer: 'CardioWave',
    model: 'WaveTrace 12',
    serialNumber: 'CW-WT-55902',
    status: 'maintenance',
    ward: 'Cardiology',
    firmware: '1.9.4',
    lastSeen: Date.now() - 1000 * 60 * 90,
    metrics: { heartRate: 0, battery: 45 },
    alerts: [
      {
        id: 'al-2',
        severity: 'info',
        message: 'Scheduled calibration due in 2 days',
        timestamp: Date.now() - 1000 * 60 * 60,
        acknowledged: true,
      },
    ],
  },
  {
    id: 'dev-po-005',
    name: 'Pulse Ox E5',
    type: 'pulse_oximeter',
    manufacturer: 'OxySense',
    model: 'PulseLite Mini',
    serialNumber: 'OS-PL-77331',
    status: 'offline',
    ward: 'ER',
    bed: 'ER-06',
    firmware: '2.1.0',
    lastSeen: Date.now() - 1000 * 60 * 25,
    metrics: { spo2: 0, heartRate: 0, battery: 12 },
    alerts: [
      {
        id: 'al-3',
        severity: 'critical',
        message: 'Device disconnected unexpectedly',
        timestamp: Date.now() - 1000 * 60 * 25,
        acknowledged: false,
      },
    ],
  },
  {
    id: 'dev-bp-006',
    name: 'BP Monitor F6',
    type: 'blood_pressure',
    manufacturer: 'Pressura',
    model: 'BP-Check Ultra',
    serialNumber: 'PR-BC-44108',
    status: 'online',
    ward: 'Ward 1',
    bed: 'W1-08',
    firmware: '3.0.2',
    lastSeen: Date.now(),
    connectedAt: Date.now() - 1000 * 60 * 15,
    metrics: { systolic: 134, diastolic: 86, heartRate: 72, battery: 81 },
    alerts: [],
  },
];

export const DISCOVERABLE: ScanResult[] = [
  {
    id: 'scan-df-001',
    name: 'Defibrillator G7',
    type: 'defibrillator',
    manufacturer: 'ShockSafe',
    model: 'LifePulse AED',
    signalStrength: 78,
    protocol: 'BLE',
  },
  {
    id: 'scan-pm-002',
    name: 'Bedside Monitor A7',
    type: 'patient_monitor',
    manufacturer: 'MediCore',
    model: 'VitaLink Pro 450',
    signalStrength: 92,
    protocol: 'Wi-Fi',
  },
  {
    id: 'scan-ip-003',
    name: 'Infusion Pump B9',
    type: 'infusion_pump',
    manufacturer: 'FlowMed',
    model: 'InfuSmart X9',
    signalStrength: 64,
    protocol: 'HL7',
  },
];
